Controllers/EventController.cs
using L_MOBILE_MARATHON.Data;
using L_MOBILE_MARATHON.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Dynamic;
using System.Reflection;
using System.Text;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace L_MOBILE_MARATHON.Controllers
{
	public class EventController : Controller
	{
		private readonly ApplicationDbContext _db;
		public EventController(ApplicationDbContext db)
		{
			_db = db;
		}
		// GET: EventsController
		public IActionResult Index(string? eventNameFilter = "", string? statusFilter = "", DateTime? startDateFilter = null, int pg=1)
		{
			IQueryable<Event> objEvents = _db.Events.AsQueryable();
			foreach(var obj in objEvents)
			{
                if (obj.Status == "open" && obj.Start < DateTime.Today)
                {
                    obj.Status = "closed";
                    _db.Events.Update(obj);
                }
            }
            _db.SaveChanges();


            //Filter;
            if (!string.IsNullOrEmpty(eventNameFilter))
			{
				objEvents = objEvents.Where(e => e.EventName.ToLower().Contains(eventNameFilter.ToLower()));
			}
			if (!string.IsNullOrEmpty(statusFilter))
			{
				objEvents = objEvents.Where(e => e.Status.ToLower() == statusFilter.ToLower());
			}

			if (startDateFilter.HasValue)
			{
				objEvents = objEvents.Where(e => e.Start.Date == startDateFilter.Value.Date);
			}

			const int pageSize = 10;
			// This not required but if the user trys to send the wrong parameters to the application 
			// This line will prevent this 
			if (pg < 1)
				pg = 1;
			int recsCount = objEvents.Count();
			var pager = new Pager(recsCount, pg, pageSize);
			int recSkip = (pg - 1) * pageSize;
			var data = objEvents.Skip(recSkip).Take(pager.PageSize).ToList();
			this.ViewBag.Pager = pager;
			/*
			if (!string.IsNullOrEmpty(eventNameFilter))
			{
				this.ViewBag.NameFilter = eventNameFilter;
				objEvents  = objEvents.Where(e => e.EventName.ToLower().Contains(eventNameFilter.ToLower())).ToList();
			}*/
			return View(data);
		}
		// Create an event
		public IActionResult Create(EventViewModel obj)
		{
			return View(obj);
		}
		[HttpPost]
		public IActionResult Create(EventViewModel obj, string[] EventType)
		{
			if (obj.Event.Start > obj.Event.End)
			{
				TempData["Error"] = "Start Date must less than End Date";
				return View(obj);
			}
			/*
			if (EventType == null)
			{
				TempData["Error"] = "You should choose at least one Event type";
				return View(obj);
			}
			*/
			if (ModelState.IsValid)
			{
				_db.Events.Add(obj.Event);
				_db.SaveChanges();

				foreach (var eventType in EventType)
				{
					var eventAttribute = new EventAttribute
					{
						Type = eventType,
						EventFK = obj.Event.Id
					};
					_db.EventAttributes.Add(eventAttribute);
				}

				_db.SaveChanges();
				TempData["Success"] = "Event is created successfully";
				return RedirectToAction("Index");
			}

			return View();
		}

		// Update an Event
		public IActionResult Edit(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var eventToEdit = _db.Events.Find(id);
			if (eventToEdit == null)
			{
				return NotFound();
			}

			var eventAttributes = _db.EventAttributes.Where(ea => ea.EventFK == id).ToList();

			// Create a dictionary to hold checkbox states

			var eventViewModel = new EventViewModel
			{
				Event = eventToEdit,
				EventAttribute = eventAttributes
			};

			return View(eventViewModel);
		}

		[HttpPost]
		public IActionResult Edit(EventViewModel obj)
		{
			//check this function
			if (ModelState.IsValid)
			{
				_db.Events.Update(obj.Event);

				int id = obj.Event.Id;
		
				_db.SaveChanges(); 
				TempData["Success"] = "Event updated successfully";
				return RedirectToAction("Index");
			}
			return View();
		}
		
		[HttpPost, ActionName("Delete")]
		public IActionResult DeletePost(int? id)
		{
			Event? eventObj = _db.Events.Find(id);

			if (eventObj == null)
			{
				return NotFound();
			}
			var eventAttributes = _db.EventAttributes.Where(ea => ea.EventFK == id).ToList(); ;
			// Remove the retrieved EventAttributes
			_db.EventAttributes.RemoveRange(eventAttributes);
			// Save changes to the database
			_db.SaveChanges();
			_db.Events.Remove(eventObj);
			_db.SaveChanges();
			TempData["Success"] = "Event deleted succefully";
			return RedirectToAction("Index");
		}
	}
}

Controllers/ParticipantController.cs
using L_MOBILE_MARATHON.Data;
using L_MOBILE_MARATHON.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace L_MOBILE_MARATHON.Controllers
{
    public class ParticipantController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ParticipantController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET: ParticipantController
        public ActionResult Index(string? FirstNameFilter = "", string? SecondNameFilter = "", DateOnly? BirthFilter = null, int pg=1)
        {
			List<Participant> objParticipants = _db.Participants.ToList();

			if (!string.IsNullOrEmpty(FirstNameFilter))
			{
				objParticipants = (List<Participant>)objParticipants.Where(e => e.FirstName.ToLower().Contains(FirstNameFilter.ToLower()));
			}
			if (!string.IsNullOrEmpty(SecondNameFilter))
			{
				objParticipants = (List<Participant>)objParticipants.Where(e => e.SecondName.ToLower().Contains(SecondNameFilter.ToLower()));
			}
			if (BirthFilter.HasValue)
			{
				objParticipants = (List<Participant>)objParticipants.Where(e => e.Birthday == BirthFilter.Value);
			}
			//For Pagination
			const int pageSize = 10;
			
			if (pg < 1)
				pg = 1;
			int recsCount = objParticipants.Count();
			var pager = new Pager(recsCount, pg, pageSize);
			int recSkip = (pg - 1) * pageSize;
			var data = objParticipants.Skip(recSkip).Take(pager.PageSize).ToList();
			this.ViewBag.Pager = pager;
			return View(data);
        }
        // Create a Participant
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Participant obj)
        {
            if (ModelState.IsValid)
            {
                _db.Participants.Add(obj);
                _db.SaveChanges();
                TempData["Success"] = "Participant is created succefully";
                return RedirectToAction("Index");
            }
            return View();
        }
        // Update a Participant
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Participant? user = _db.Participants.FirstOrDefault(u => u.Id == id);

            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }
        [HttpPost]
        public IActionResult Edit(Participant obj)
        {
            if (ModelState.IsValid)
            {
                _db.Participants.Update(obj);
                _db.SaveChanges();
                TempData["Success"] = "Participant updated succefully";

                return RedirectToAction("Index");
            }
            return View();
        }
        
        // Delete an Event
        public IActionResult Details(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Participant? obj = _db.Participants.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpPost]
        public IActionResult Delete(int? id)
        {
            Participant? obj = _db.Participants.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Participants.Remove(obj);
            _db.SaveChanges();
            TempData["Success"] = "Participant deleted succefully";

            return RedirectToAction("Index");
        }

    }
}

Controllers/ParticipantrunController.cs
using L_MOBILE_MARATHON.Data;
using L_MOBILE_MARATHON.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace L_MOBILE_MARATHON.Controllers
{
	public class ParticipantrunController : Controller

	{
		private readonly ApplicationDbContext _db;
		public ParticipantrunController(ApplicationDbContext db)
		{
			_db = db;
		}

		// GET: Display Participantsruns 
		public ActionResult Index(string? eventNameFilter = "", string? eventAttributeFilter = "", string? emailFilter = "")
		{
			var query = from r in _db.Participantsruns
						join a in _db.EventAttributes on r.EventAttributeFK equals a.Id
						join p in _db.Participants on r.ParticipantFK equals p.Id
						join e in _db.Events on a.EventFK equals e.Id
						select new
						{
                            Id = r.Id,
							EventName = e.EventName,
							Distance = a.Type,
							Email = p.Email,
							ParticipationDate = e.Start,
							Status = r.Status
						};

			// Apply filters
			if (!string.IsNullOrEmpty(eventNameFilter))
			{
				query = query.Where(e => e.EventName.ToLower().Contains(eventNameFilter.ToLower()));
			}
			if (!string.IsNullOrEmpty(eventAttributeFilter))
			{
				query = query.Where(e => e.Distance.ToLower() == eventAttributeFilter.ToLower());
			}
			if (!string.IsNullOrEmpty(emailFilter))
			{
				query = query.Where(e => e.Email.ToLower() == emailFilter.ToLower());
			}

			var objParticipantsruns = query.ToList();
            ViewBag.Participantsruns = objParticipantsruns;

			return View();
		}

		// Create a participant run
		public IActionResult Create()
        {
            return View();
        } 
        [HttpPost]
        public IActionResult Create(Participantsrun obj)
        {
            if (ModelState.IsValid)
            {
                _db.Participantsruns.Add(obj);
                _db.SaveChanges();
                TempData["Success"] = "Run is created succefully";
                return RedirectToAction("Index");
            }
            return View();
        }
        // Update a participant run
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Participantsrun? run = _db.Participantsruns.FirstOrDefault(u => u.Id == id);

            if (run == null)
            {
                return NotFound();
            }
            return View(run);
        }
        [HttpPost]
        public IActionResult Edit(Participantsrun obj)
        {
            if (ModelState.IsValid)
            {
                _db.Participantsruns.Update(obj);
                _db.SaveChanges();
                TempData["Success"] = "Run updated succefully";

                return RedirectToAction("Index");
            }
            return View();

        }
        // Delete a participant run
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Participantsrun? categoryFromDb = _db.Participantsruns.Find(id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Participantsrun? obj = _db.Participantsruns.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Participantsruns.Remove(obj);
            _db.SaveChanges();
            TempData["Success"] = "Run deleted succefully";

            return RedirectToAction("Index");
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - L_MOBILE_MARATHON</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/L_MOBILE_MARATHON.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">L_MOBILE_MARATHON</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="Index">Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Participant" asp-action="Index">Participants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Participantrun" asp-action="Index">Participantrun</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
        <div class="container">
            <main role="main" class="pb-3">
                <partial name="_Notification" />
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2024 - L_MOBILE_MARATHON 
            </div>
        </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@* for all the reusable elements we use partial views *@

@if (TempData["success"] != null)

{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js">
	</script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]');
	</script>
}
@if (TempData["error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.error('@TempData["error"]');
	</script>
}